### ISSUE TITLE
Performance Enhancement

### ISSUE THREAD

**Issue by SimonLentner** [Uberton/Uberton#1]
* Immediately: Do we compute the eigenfunctions on the position of speaker and listener each call or only if it is changed?

* Save only linear combination of eigenvalues, and evolve them. For input in every step, use a saved matrix linking audio sources to audio . Disadvantage: If we change location, we cannot save the history but have to start fresh
 * work with wavelets to allow microscopic frequencies and macroscopic frequencies (echo)

**Comment by Mc-Zen** [comment]
Eigenfunction evaluations of input and ouput positions are already computed once and stored. 
Now, the exponential time expressions exp(iωt) are buffered as well which results in a performance improvement of at least about 10 times as measured.
