### ISSUE TITLE
have Latency popping 

### ISSUE THREAD

**Issue by subapilot** [Uberton/Uberton#20]
when i open the tesseract i get pops. how not do?

**Comment by Mc-Zen** [comment]
Hi @subapilot ,

There can be a few reasons for that. 
1. The CPU just can't handle Tesseract at the current setting. 

Let's do some troubleshooting. What DAW are you using? Can you open some indicator for the real-time performance? For example, in Cubase/Nuendo, you can press F12 to open a small window that shows the CPU utilization in detail. If it peaks or is operating at a very high load you can try the following two things
- Reduce the "Order" parameter of Tesseract. It determines how many "waves" are added in the simulation. This will reduce the number of overtones you hear but also reduce the CPU load. 
- Increase the buffer size for your audio card. At low values (say 128 samples or less), the real-time load on the CPU is much higher. Try 512 or 1024 samples. 


2. Audio pops can also happen when another program is using the audio driver at the same time or when some components of the computer are not well tuned to each other. You can rule out this cause of the pops by removing the Tesseract plugin and maybe running some other plugin instead. 

Does any of that help? Of course, please get back to me if you don't understand some of the terminology.

**Comment by subapilot** [comment]
im using Reaper

reduced order to 1 - still much crackle

running reaper alone up 7-10% cpu, 57.2% memory 53mb
w/ tesseract  20%cpu 70% memory 75.4mb

switch to 512 worked!

**Comment by Mc-Zen** [comment]
Excellent! What was the setting before you changed it to 512? Were you able to increase the order parameter again without the cracks returning? 

On a sidenote (you might know already): For audio processing, you usually need a processor with a good _single-core performance_ , for example 4x2.7GHz (4-core processor) is better than 8x1.3GHZ (8 cores) because certain things in audio cannot be distributed across multiple processor cores.

**Comment by subapilot** [comment]
yes i can play with the order parameter, no pops that i know of yet 

i was either at 48 or 64, cant remember. 

i have a core i7, 7th gen - google tells me i have 4 cores/8 threads.. good?

**Comment by Mc-Zen** [comment]
> i have a core i7, 7th gen - google tells me i have 4 cores/8 threads.. good?

Yes this is a good processor for this application!

> i was either at 48 or 64, cant remember.

Okay, that was the issue then, 64 is really low, barely a millisecond.
